import Head from 'next/head'
import AttentionCatcher from '../components/AttentionCatcher'
import Benefits from '../components/Benefits'
import Features from '../components/Features'
import Hero from '../components/Hero'
import Princing from '../components/Pricing'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <AttentionCatcher />
      <Benefits />
      <Princing />
      <Features />
    </div>
  )
}
